<?php

return [
    'verify_seed' => env('GIS_VERIFY_SEED', false),
    'seed_enabled' => env('GIS_SEED_ENABLED', true),
    'seed_path' => database_path('seeders/data/gis-astana'),
    'seed_max_bytes' => 50_000_000,
    'seed_tile_zoom' => 13,
    'seed_sources' => [
        'Hosted/raiony/FeatureServer/0',
        'Hosted/basemap_ast_03052023/VectorTileServer',
        'dop_sloi_geoportal_otkr/MapServer/0',
        'dop_sloi_geoportal_otkr/MapServer/5',
        'dop_sloi_geoportal_otkr/MapServer/8',
        'dop_sloi_geoportal_otkr/MapServer/12',
        'dop_sloi_geoportal_otkr/MapServer/14',
        'dop_sloi_geoportal_otkr/MapServer/18',
        'dop_sloi_geoportal_otkr/MapServer/19',
        'Sloi_geoportala_otkrytiy_kontur_0702/MapServer/0',
        'Sloi_geoportala_otkrytiy_kontur_0702/MapServer/30',
        'Sloi_geoportala_otkrytiy_kontur_0702/MapServer/31',
        rawurlencode('Генплан_Астаны').'/MapServer/52',
        rawurlencode('Генплан_Астаны').'/MapServer/60',
        rawurlencode('Генплан_Астаны').'/MapServer/63',
    ],
    'portal' => 'https://gis.esaulet.kz/portal',
    'maps' => ['c1d82fa0909d4fdfb6e5149bbc3bca2b', '559c4ce50e8749fd857bbf9bd6c4cf50'],
    'allowed_host' => 'gis.esaulet.kz',
    'disk' => 'local',
    'max_zoom' => 18,
    'page_size' => 1000,
    'district_source' => 'https://gis.esaulet.kz/server/rest/services/Hosted/raiony/FeatureServer/0',
    'http_timeout' => 40,
];
